-- ==========================================
-- STRUKTUR DATABASE SUPABASE UNTUK BLIGUS COFFEE
-- Anda bisa me-run (menjalankan) script SQL ini di fitur "SQL Editor" pada dashboard Supabase.
-- ==========================================

-- 1. TABEL PRODUCTS (Katalog Menu)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  price INTEGER NOT NULL,
  image_url TEXT,
  is_available BOOLEAN DEFAULT TRUE,
  badge TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABEL ORDERS (Data Pesanan)
CREATE TABLE orders (
  id TEXT PRIMARY KEY, -- Format custom, contoh: BLG-20260924-123
  customer_name TEXT NOT NULL,
  whatsapp TEXT NOT NULL,
  notes TEXT,
  total_amount INTEGER NOT NULL,
  status TEXT DEFAULT 'Menunggu Diproses', -- Menunggu Diproses, Sedang Diproses, Siap Diambil, Selesai, Dibatalkan
  payment_method TEXT DEFAULT 'QRIS',
  proof_image TEXT, -- URL gambar bukti transfer dari Supabase Storage
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL ORDER_ITEMS (Detail item untuk masing-masing pesanan)
CREATE TABLE order_items (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  order_id TEXT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL, -- Menyimpan nama snapshot agar jika nama produk berubah, histori pesanan tetap valid
  unit_price INTEGER NOT NULL, 
  quantity INTEGER NOT NULL,
  subtotal INTEGER NOT NULL,
  add_ons JSONB DEFAULT '[]'::jsonb -- Format JSON array untuk mencatat add-ons: ["+1 Shot Espresso (+Rp3.000)"]
);


-- ==========================================
-- ROW LEVEL SECURITY (KEMANAN DATABASE)
-- ==========================================

-- Mengaktifkan RLS untuk semua tabel
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

-- Policy untuk Products: 
-- Siapapun (publik) bisa melihat katalog menu
CREATE POLICY "Public can view products" 
ON products FOR SELECT USING (true);

-- Policy untuk Orders: 
-- Pembeli (publik) hanya bisa membuat pesanan (insert)
CREATE POLICY "Public can insert orders" 
ON orders FOR INSERT WITH CHECK (true);

-- (Opsional) Jika pembeli butuh cek status pesanan mereka
CREATE POLICY "Public can view their own orders" 
ON orders FOR SELECT USING (true);

-- Policy untuk Order Items:
-- Pembeli (publik) hanya bisa menambahkan item ke pesanan
CREATE POLICY "Public can insert order items" 
ON order_items FOR INSERT WITH CHECK (true);

-- (Opsional) Jika pembeli butuh cek item pesanan mereka
CREATE POLICY "Public can view order items" 
ON order_items FOR SELECT USING (true);

-- ==========================================
-- CATATAN UNTUK ADMIN:
-- Secara default, Anda akan menggunakan Supabase Service Role Key di server (Next.js API route) 
-- untuk membaca & meng-update data Orders (mengubah status), sehingga tidak memerlukan Policy RLS tambahan untuk Admin.
-- ==========================================
