INSERT INTO products (id, name, category, description, price, image_url, is_available, badge) VALUES
(1, 'Kopi Susu BliGus', 'Signature Series', 'Signature kopi susu khas BliGus dengan rasa creamy, gurih, dan manis pas yang nikmat.', 18000, '/images/products/kopi_susu_bligus.png', true, 'Best Seller'),
(2, 'Golden Caramel', 'Signature Series', 'Perpaduan kopi susu lembut dengan topping caramel crumble renyah dan lelehan saus karamel gurih.', 20000, '/images/products/golden_caramel.png', true, 'Best Seller'),
(3, 'Klepon Macchiato', 'Signature Series', 'Inovasi unik rasa klepon tradisional perpaduan espresso, wangi pandan, dan kelapa gula aren lembut.', 22000, '/images/products/klepon_macchiato.png', true, NULL),
(4, 'Burnt Aren', 'Signature Series', 'Kopi susu gula aren spesial dengan lapisan brulee burnt aren karamelisasi di atas foam.', 22000, '/images/products/burnt_aren.png', true, NULL),
(5, 'Cafe Latte', 'Coffee Series', 'Espresso klasik berpadu steamed fresh milk dengan tekstur lembut, creamy, dan seimbang.', 12000, '/images/products/kopi_susu_bligus.png', true, NULL),
(6, 'Cappuccino', 'Coffee Series', 'Espresso mantap dengan microfoam susu tebal bertabur bubuk cokelat aromatik pilihan.', 15000, '/images/products/cappuccino.png', true, 'Best Seller'),
(7, 'Dalgona', 'Coffee Series', 'Susu segar dingin creamy dengan whipped dalgona coffee foam kental manis di atasnya.', 13000, '/images/products/dalgona.png', true, NULL),
(8, 'Caramel', 'Coffee Series', 'Kopi susu dengan saus karamel manis legit yang harum dan memanjakan lidah.', 15000, '/images/products/caramel.png', true, 'Best Seller'),
(9, 'Hazelnut', 'Coffee Series', 'Kopi susu nikmat berpadu sirup hazelnut panggang dengan aroma nutty yang khas dan gurih.', 15000, '/images/products/hazelnut.png', true, NULL),
(10, 'Butterscotch', 'Coffee Series', 'Paduan kopi susu dengan rasa butterscotch manis gurih mentega karamel khas cafe.', 15000, '/images/products/butterscotch.png', true, NULL),
(11, 'Gula Aren', 'Coffee Series', 'Kopi susu klasik dipadukan dengan manis alami gula aren asli nusantara yang harum.', 15000, '/images/products/gula_aren.png', true, 'Best Seller'),
(12, 'Dirty Matcha', 'Coffee Series', 'Kombinasi unik matcha Jepang pekat dengan espresso shot dan susu segar berlapis.', 15000, '/images/products/dirty matcha.png', true, NULL),
(13, 'Moccacino', 'Coffee Series', 'Kombinasi klasik espresso beraroma cokelat pekat dan susu segar yang kaya rasa.', 15000, '/images/products/moccacino.png', true, NULL),
(14, 'Coconut Aren', 'Coffee Series', 'Sensasi kopi susu gula aren dengan sentuhan rasa kelapa tropis yang segar dan gurih.', 15000, '/images/products/coconut_aren.png', true, 'New'),
(15, 'Butterpalm', 'Coffee Series', 'Kombinasi butter caramel gurih dengan manisnya gula palm aren alami yang menggoda.', 15000, '/images/products/butter_palm.png', true, 'New'),
(16, 'Pandan', 'Coffee Series', 'Kopi susu beraroma daun pandan wangi yang menenangkan dan menyegarkan harimu.', 15000, '/images/products/pandan.png', true, 'New'),
(17, 'Berry-Cano', 'Americano Series', 'Espresso dipadukan dengan kesegaran sari buah beri manis asam yang menyegarkan dahaga.', 15000, '/images/products/berrycano.png', true, 'Best Seller'),
(18, 'Apple-Cano', 'Americano Series', 'Perpaduan espresso beraroma tajam dengan jus apel segar manis alami yang unik.', 15000, '/images/products/AppleCano.png', true, NULL),
(19, 'Orange-Cano', 'Americano Series', 'Sensasi citrus jeruk manis segar berpadu dengan espresso dingin yang aromatik.', 15000, '/images/products/OrangeCano.png', true, NULL),
(20, 'Americano', 'Americano Series', 'Espresso murni dengan tambahan air dingin/panas, aroma kuat dan crema tebal mantap.', 10000, '/images/products/americano.png', true, NULL),
(21, 'Matcha', 'Non-Coffee Series', 'Matcha premium berkualitas dengan susu segar creamy, kaya antioksidan tanpa kandungan kopi.', 12000, '/images/products/matcha.png', true, 'Best Seller'),
(22, 'Chocolate', 'Non-Coffee Series', 'Cokelat pekat pilihan yang manis dan legit dipadukan dengan susu segar yang memanjakan.', 12000, '/images/products/Chocolate.png', true, NULL),
(23, 'Double Choco', 'BliGus Gabin', 'Gabin renyah dengan isian double choco yang lumer dan nikmat.', 12000, '/images/products/Double_Choco.PNG', true, NULL),
(24, 'Matcha Crunch', 'BliGus Gabin', 'Gabin dengan isian matcha crunch manis khas BliGus.', 12000, '/images/products/Matcha_Crunch.PNG', true, NULL),
(25, 'Cookies & Cream', 'BliGus Gabin', 'Gabin dengan isian cookies & cream spesial.', 12000, '/images/products/Cookies&Cream.PNG', true, NULL),
(26, 'Salted Caramel', 'BliGus Gabin', 'Gabin dengan isian salted caramel yang manis gurih.', 12000, '/images/products/Salted_Caramel.PNG', true, NULL),
(27, 'Cheese Regal', 'BliGus Gabin', 'Gabin dengan isian cheese regal yang nikmat.', 12000, '/images/products/Cheese_Regal.PNG', true, NULL),
(28, 'Tiramisu', 'BliGus Gabin', 'Gabin renyah dengan rasa tiramisu premium.', 12000, '/images/products/Tiramisu_Gabin.PNG', true, NULL),
(29, 'BliGus 1', 'Combo / Bundling', '2 pcs Gabin + Kopi Susu BliGus', 40000, '/images/products/BliGus_Combo_1.PNG', true, NULL),
(30, 'BliGus 2', 'Combo / Bundling', '1 pcs Gabin + Golden Caramel', 30000, '/images/products/BliGus_Combo_2.PNG', true, NULL);
